product-name: application
# possible levels:  error, warn, info, verbose, debug, silly
log-level: info
port: 4000
hostname: localhost
uploader: false
library: [/home/svandeca/Musique]
audio: [mp3,  wav, wma, ogg, flac]
video: [mp4, webm, flv, ogv, mpg]
defaultLanguage: fr
database: redis
type: browser
playingtype: streaming
redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
secret: eba16c61-18db-471a-9406-6371d7e42f63
bcrypt_rounds: 12
gravatar: true
local: false
requireLogin: false
allowUpload: true
allowRegisteration: 3
third-party:
    spotify:
        clientId:
        secret:
    lastfm:
        api-key:
        secret:
theme:
  base-color: rgb(230, 217, 45)
