default:
  database:
    host: localhost
    database: test-ongaku
    username: test-ongaku
    password:
    logging: false
    dialect: postgres
    dialectOptions:
      multipleStatements: true
  port: 4000
development:
  database:
    host: localhost
    database: test-ongaku
    username: test-ongaku
    password:
    logging: false
    dialect: postgres
    dialectOptions:
      multipleStatements: true
  port: 4000
unit-testing:
  database:
    database: angular
    username: svandecappelle
    password: null
    logging: false
    dialect: sqlite
    storage: test.db
    dialectOptions:
      multipleStatements: true
  port: 4000
testing:
  database:
    host: localhost
    database: test-ongaku
    username: test-ongaku
    password:
    logging: false
    dialect: postgres
    dialectOptions:
      multipleStatements: true
  port: 4000